services:
  mysql:
    build:
      ./mysql-database
    ports:
      - 3306:3306
  user:
    build:
      ./stampmarket-user
    ports:
      - 9001:9001
    depends_on:
      - mysql
      - eureka
  stamp:
    build:
      ./stampmarket-stamp
    ports:
      - 9002:9002
    depends_on:
      - mysql
      - eureka
  eureka:
    build:
      ./stampmarket-eureka
    ports:
      - 7000:7000
  gateway:
    build:
      ./stampmarket-gateway
    ports:
      - 8222:8222
    depends_on:
      - eureka