services:
  mysql:
    build:
      ./mysql-database
    ports:
      - 3306:3306
  user:
    build:
      ./stampmarket-user
    ports:
      - 9001:9001
    depends_on:
      - mysql
  stamp:
    build:
      ./stampmarket-stamp
    ports:
      - 9002:9002
    depends_on:
      - mysql
  order:
    build:
      ./stampmarket-order
    ports:
      - 9003:9003
    depends_on:
      - mysql