services:
  mysql:
    build:
      ./mysql-database
    ports:
      - 3306:3306
  user:
    build:
      ./stampmarket-user
    ports:
      - 9001:9001
  stamp:
    build:
      ./stampmarket-stamp
    ports:
      - 9002:9002
  stamp-spare:
    build:
      ./stampmarket-stamp
    ports:
      - 8002:9002
  eureka:
    build:
      ./stampmarket-eureka
    ports:
      - 7000:7000
  order:
    build:
      ./stampmarket-order
    ports:
      - 9003:9003