server:
  port: 8222
spring:
  application:
    name: gateway

# 服务注册中心地址
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:7000/eureka
  instance:
    prefer-ip-address: true

# 网关配置
#zuul:
#  routes:
#    stamp:
#      path: /stamp
#      serviceId: stamp
#    user:
#      path: /user
#      serviceId: user
#    order:
#      path: /order
#      serviceId: order
#    pay:
#      path: /pay
#      serviceId: pay