server:
  port: 9002
spring:
  application:
    name: stamp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/stamp_market
    username: root
    password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:7000/eureka
  instance:
    prefer-ip-address: true
